name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            msystem: MINGW64
            arch: x86_64
            shell: msys2 {0}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: git base-devel mingw-w64-${{ matrix.arch }}-toolchain
          update: true
      - name: Build jq
        shell: ${{ matrix.shell }}
        run: ./build.sh
      - uses: actions/setup-python@v2
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      - name: Install Windows build dependencies
        if: runner.os == 'Windows'
        run: choco install vcpython27 -f -y
      - name: Install macOS build dependencies
        if: runner.os == 'macOS'
        run: brew install automake
      - name: Build wheels
        env:
          CIBW_TEST_REQUIRES: "-r test-requirements.txt"
          CIBW_TEST_COMMAND: "nosetests {project}/tests"
        run: python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
